#+TITLE: Take Home Initial Exam Winter 2019
#+AUTHOR: Rick Neff
#+EMAIL: NeffR@byui.edu
#+LANGUAGE: en
#+OPTIONS: H:5 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t ':t

* Instructions
  Please analyze and reason carefully, making full use of the *mind tools* in
  your possession:

  The philosopher John Locke wrote in 1690 about three mind tools (which he
  called acts) in /An Essay Concerning Human Understanding/:
#+BEGIN_QUOTE
 The acts of the mind, wherein it exerts its power over simple ideas, are
 chiefly these three:

 1. Combining several simple ideas into one compound one, and thus all complex
    ideas are made.
 2. The second is bringing two ideas, whether simple or complex, together, and
    setting them by one another so as to take a view of them at once, without
    uniting them into one, by which it gets all its ideas of relations.
 3. The third is separating them from all other ideas that accompany them in
    their real existence: this is called abstraction, and thus all its general
    ideas are made.
#+END_QUOTE

** Reading
  - Robert B. Laughlin's [[https://rickneff.github.io/computer-musings.pdf][Computer Musings]]
  - David Wick on [[https://rickneff.github.io/philosophical-computation.pdf][Philosophical Computation]]
  - Technical Opinion of Peter Wegner and Dina Goldin on [[https://rickneff.github.io/computation-beyond-turing-machines.pdf][Computation Beyond Turing Machines]]

** Writing
  Using the above three sources, and from what you already know about
  computation, complexity and other theoretical computer science topics, discuss
  the computational and philosophical implications of randomness and sentience,
  and describe how computational theory and practice affect your attitudes and
  mindset. Specifically, answer the three questions below:

  1. What do *you* think are appropriate methods to model computing and human thought?
  2. Are you a realist or an instrumentalist?
  3. Would you rather have computers be more like cats or like dogs?!
